version: "3"
services:
  front:
    build: .
    tty: true
    ports:
      - "3000:3000" # for development
      - "4000:4000" # for production
    volumes:
      - ./app:/app
      - front_node_modules:/app/node_modules
    command: yarn dev
volumes:
  front_node_modules: # volume trick