version: "3"
services:
  front:
    build: .
    tty: true
    ports:
      - "3000:3000" # for development
      - "4000:4000" # for production
    volumes:
      - ./app/datetime_to_decimal_number_calculator:/app
    command: yarn dev